// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSza7DovPgaSp0y7qreg8i2LE8f4SNP0',
    appId: '1:533939124310:web:8be73689f421443dd823f7',
    messagingSenderId: '533939124310',
    projectId: 'mental-health-chatbot-87bdf',
    authDomain: 'mental-health-chatbot-87bdf.firebaseapp.com',
    databaseURL: 'https://mental-health-chatbot-87bdf.firebaseio.com',
    storageBucket: 'mental-health-chatbot-87bdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TF8YYZ3KsxwxYjaZ_DqtmN-b5lqpr8E',
    appId: '1:533939124310:android:57175f2ad0ecc80dd823f7',
    messagingSenderId: '533939124310',
    projectId: 'mental-health-chatbot-87bdf',
    databaseURL: 'https://mental-health-chatbot-87bdf.firebaseio.com',
    storageBucket: 'mental-health-chatbot-87bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Nmou6t48-of6jMT2zArvgNwGkTST1GQ',
    appId: '1:533939124310:ios:8e6630ef7086e81fd823f7',
    messagingSenderId: '533939124310',
    projectId: 'mental-health-chatbot-87bdf',
    databaseURL: 'https://mental-health-chatbot-87bdf.firebaseio.com',
    storageBucket: 'mental-health-chatbot-87bdf.appspot.com',
    iosClientId: '533939124310-ss5auv701vljd0lfmo6fh48sq2sa3e41.apps.googleusercontent.com',
    iosBundleId: 'com.mentalhealth.app',
  );
}
